// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $body, $entrant1input, $entrant2input, $form, $status, entrants, socket;
    $body = $.one("body");
    $status = $.one("#status");
    $form = $.one("#battle-setup");
    $entrant1input = $.one("#entrant1-input");
    $entrant2input = $.one("#entrant2-input");
    entrants = {
      entrant1: {
        $name: $.one("#entrant1 .name"),
        $count: $.one("#entrant1 .count"),
        $tweets: $.one("#entrant1 .tweets")
      },
      entrant2: {
        $name: $.one("#entrant2 .name"),
        $count: $.one("#entrant2 .count"),
        $tweets: $.one("#entrant2 .tweets")
      }
    };
    socket = io.connect();
    socket.on('connect', function() {
      return $status.html("Connected");
    });
    $form.submit(function() {
      $status.html("Starting battle");
      socket.emit('battle-setup', {
        entrant1: $entrant1input.val(),
        entrant2: $entrant2input.val()
      });
      return false;
    });
    socket.on('battle-start', function(msg) {
      $status.html("Battle started");
      entrants.entrant1.$name.html(msg.entrant1);
      entrants.entrant2.$name.html(msg.entrant2);
      return $body.attr("class", "battling");
    });
    return socket.on('tweet', function(msg) {
      var $newTweet, entrant, _ref;
      console.log("tweet", msg);
      entrant = entrants[msg.which];
      entrant.$count.text(msg.count);
      $newTweet = $('<div class="tweet"></div>');
      return entrant.$tweets.prepend($newTweet.text((_ref = msg.tweet) != null ? _ref : "Let the tweets begin!"));
    });
  });

}).call(this);
