// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $body, $entrant1input, $entrant2input, $form, $status, entrants, socket;
    $body = $.one("body");
    $status = $.one("#status");
    $form = $.one("#battle-setup");
    $entrant1input = $.one("#entrant1-input");
    $entrant2input = $.one("#entrant2-input");
    entrants = {
      entrant1: {
        $name: $.one("#entrant1 .name"),
        $count: $.one("#entrant1 .count"),
        $tweets: $.one("#entrant1 .tweets")
      },
      entrant2: {
        $name: $.one("#entrant2 .name"),
        $count: $.one("#entrant2 .count"),
        $tweets: $.one("#entrant2 .tweets")
      }
    };
    socket = io.connect();
    socket.on('connect', function() {
      return $status.html("Connected");
    });
    $form.submit(function() {
      $status.html("Starting battle");
      socket.emit('battle-setup', {
        entrant1: $entrant1input.val(),
        entrant2: $entrant2input.val()
      });
      return false;
    });
    socket.on('setup-info', function(msg) {
      var $top_battles, b, _fn, _i, _len, _ref;
      $top_battles = $("#top_battles");
      debugger;
      _ref = msg.top_battles;
      _fn = function(b) {
        var $e;
        $e = $("<a>" + b[0] + " vs " + b[1] + "</a>");
        $e.click(function() {
          $entrant1input.val(b[0]);
          $entrant2input.val(b[1]);
          return $form.submit();
        });
        return $top_battles.append($e);
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        b = _ref[_i];
        _fn(b);
      }
      return $top_battles.show();
    });
    socket.on('battle-start', function(msg) {
      var $newTweet, key, tweet, _i, _j, _len, _len1, _ref, _ref1;
      $status.html("Battle started");
      _ref = ['entrant1', 'entrant2'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        key = _ref[_i];
        entrants[key].$name.html(msg[key].hashtag);
        entrants[key].$count.html(msg[key].count);
        _ref1 = msg[key].recent || [];
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          tweet = _ref1[_j];
          $newTweet = $('<div class="tweet"></div>');
          entrants[key].$tweets.append($newTweet.text(tweet));
        }
      }
      return $body.attr("class", "battling");
    });
    return socket.on('tweet', function(msg) {
      var $newTweet, entrant, _ref;
      console.log("tweet", msg);
      entrant = entrants[msg.which];
      entrant.$count.text(msg.count);
      $newTweet = $('<div class="tweet"></div>');
      return entrant.$tweets.prepend($newTweet.text((_ref = msg.tweet) != null ? _ref : "Let the tweets begin!"));
    });
  });

}).call(this);
